### ISSUE TITLE
Object.require is deprecated.

### ISSUE THREAD

**Issue by n0n1** [m1ga/ti-create#14]
Use `remote.Dialog` instead of `remote.require("dialog")`
```
Object.require (/Applications/Atom.app/Contents/Resources/app.asar/src/electron-shims.js:57:12)
Object.<anonymous> (/Users/n0n1/.atom/packages/ti-create/lib/ti-create.js:6:21)
Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:109:30)
Object..js (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
Module.load (module.js:473:32)
tryModuleLoad (module.js:432:12)
```

**Comment by m1ga** [comment]
Which atom version are you using? With 1.15.0 I don't get any deprecated error when using the latest ti-create.

**Comment by n0n1** [comment]
Hi, @m1ga . Are you right! Sorry

**Comment by n0n1** [comment]
@m1ga Atom 1.15.0. http://take.ms/I6V8S 
Anyway %)

**Comment by m1ga** [comment]
please check your ti-create version. Line 6 already has `dialog = remote.dialog` 😄 0.29.0 is the newest and I'm using it with the same Atom version (Linux) without a deprecation warning

**Comment by n0n1** [comment]
hm. ok. failed finds update. https://atom.io/packages/ti-create have 0.26.0

**Comment by n0n1** [comment]
@m1ga strange. I don't know why I  have deprecated package of atom-beautify. But now it ok. Also http://take.ms/FrutA have 0.26.0 version.

**Comment by m1ga** [comment]
oh, strange. I've published another update

**Comment by n0n1** [comment]
Thanks @m1ga. All good :) 0.30 version.

**Comment by m1ga** [comment]
Awesome! But still strange 😄
