### ISSUE TITLE
Installing “ti-create@0.19.0” failed

### ISSUE THREAD

**Issue by gaugau3000** [m1ga/ti-create#4]
Hi,

i have a bug installaing the ti-create package.

Many tks 4 your help.

> runas@2.0.0 install C:\Users\gautier\AppData\Local\Temp\apm-install-dir-11588-4628-19o8hhd\node_modules\ti-create\node_modules\pathwatcher\node_modules\runas
> node-gyp rebuild

C:\Users\gautier\AppData\Local\Temp\apm-install-dir-11588-4628-19o8hhd\node_modules\ti-create\node_modules\pathwatcher\node_modules\runas>if not defined npm_config_node_gyp (node "C:\Users\gautier\AppData\Local\atom\app-1.0.11\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\gautier\\AppData\\Local\\atom\\app-1.0.11\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\gautier\\AppData\\Local\\atom\\app-1.0.11\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\gautier\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\gautier\\.atom\\.apmrc" "install" "C:\\Users\\gautier\\AppData\\Local\\Temp\\d-11588-4628-s2nqjt\\package.tgz" "--target=0.22.0" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.

**Comment by m1ga** [comment]
just published an update that removes pathwatcher since its included in atom. So hopefully these problems are gone now :)

**Comment by gaugau3000** [comment]
it works many tks !
